Add override option for checkbox radius
dabapps/roe pull request #346
Opened 2021-02-25 18:08 UTC by alpower

If developers increase the `@border-radius-base` it can make the border-radius of checkboxes round.

This pulls out the default checkbox border-radius into is's own variable `@checkbox-border-radius-base` to allow for counteraction of this.

![image](https://user-images.githubusercontent.com/858646/109197022-64816980-7794-11eb-834a-798f99fabee1.png)

Fixes #327

2021-02-26 12:18 UTC, JakeSidSmith requested changes
There is no small/large checkbox variant, so it makes more sense to drop the `-base`.

2021-02-26 12:18 UTC, JakeSidSmith commented on src/ts/components/forms/form-group.examples.md
> +@checkbox-border-radius-base: @border-radius-base * 2;
```suggestion
@checkbox-border-radius: @border-radius-base * 2;
```

2021-02-26 12:18 UTC, JakeSidSmith commented on src/less/variables.less
> +@checkbox-border-radius-base: @border-radius-base * 2;
```suggestion
@checkbox-border-radius: @border-radius-base * 2;
```

2021-02-26 12:18 UTC, JakeSidSmith commented on src/less/overrides.less
> +  border-radius: @checkbox-border-radius-base;
```suggestion
  border-radius: @checkbox-border-radius;
```

2021-03-02 15:55 UTC, JakeSidSmith submitted a review, later dismissed

2021-03-02 15:56 UTC, JakeSidSmith commented
@alpower can you run `npm version patch` and commit. Then I can create and publish a new release once merged.

2021-03-02 17:54 UTC, alpower commented
> @alpower can you run `npm version patch` and commit. Then I can create and publish a new release once merged.

Done thanks!

2021-03-04 10:02 UTC, JakeSidSmith approved these changes

2021-03-04 10:02 UTC, merged